### ISSUE TITLE
Wireframes, Planning important views

### ISSUE THREAD

**Issue by Carmer** [kamiboers/toolchest#1]
Think about what you think the workflow should be on the site. Which of those views is most important?
      In addition to the home page wireframe, create wireframes for the next two most important pages.
      Examples might be: A users' profile page, a product page, an admin dashboard etc...

**Comment by kamiboers** [comment]
home page: https://wireframe.cc/JaTOdL
shopping cart: https://wireframe.cc/Ln6GKQ
user dashboard: https://wireframe.cc/V4hcPz
