### ISSUE TITLE
Add feature tests for upcoming tasks (18, 19, 20)

### ISSUE THREAD

**Issue by kamiboers** [kamiboers/toolchest#22]
See each task for user stories.
 
For item quantity in the cart, edge cases include: reducing the quantities of items to zero should result in deletion, negative numbers of items are not allowed, etc.

**Comment by theonlyrao** [comment]
This branch contains tests and helper files for the waffle cards #18 #19 #20 

This branch will not be merged because of strange merge conflicts but the code will be modified and incorporated as we proceed.
